### ISSUE TITLE
Work Needed for Deno

### ISSUE THREAD

**Issue by sno2** [etienne-dldc/chemin#7]
I don't really know why this is on the [Deno plugin ecosystem](https://deno.land/x/chemin@v5.0.5/index.ts) because you are supposed to have the .ts extension in import/export urls.  I advise you read the [Deno Style Guide](https://deno.land/manual/contributing/style_guide) for contributing because there are a couple of conflicts with your code to the style guide.

**Comment by etienne-dldc** [comment]
Hi,
Yeah I tried to make this work but did not had time to finish...
I've publish a v6 and it seems to be working now... 🎉
